// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyHtCEL5Tr7xO_eL-JHFbzq5S_-WlfYCk',
    appId: '1:413952324449:android:1c04239738dd7ad0020b20',
    messagingSenderId: '413952324449',
    projectId: 'todo-tasks-app-d6055',
    storageBucket: 'todo-tasks-app-d6055.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh3JGLXADr-GjWBIvKC9Yr1bNxLg8kWw8',
    appId: '1:413952324449:ios:21b7d57c3a0cfa90020b20',
    messagingSenderId: '413952324449',
    projectId: 'todo-tasks-app-d6055',
    storageBucket: 'todo-tasks-app-d6055.firebasestorage.app',
    iosBundleId: 'com.example.todoList22',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh3JGLXADr-GjWBIvKC9Yr1bNxLg8kWw8',
    appId: '1:413952324449:ios:21b7d57c3a0cfa90020b20',
    messagingSenderId: '413952324449',
    projectId: 'todo-tasks-app-d6055',
    storageBucket: 'todo-tasks-app-d6055.firebasestorage.app',
    iosBundleId: 'com.example.todoList22',
  );
}
